Adding PR Template
AdaGold/api-muncher pull request #7
Opened 2017-04-26 03:37 UTC by CheezItMan

Added Basic PR Template.

Possibly we should add a question on Post vs Get requests, but Edamam only does get requests.

2017-04-27 20:49 UTC, kariabancroft requested changes

2017-04-27 20:49 UTC, kariabancroft commented on README.md
> +This is an individual, [stage 2](https://github.com/Ada-Developers-Academy/pedagogy/blob/master/rule-of-three.md) project.
👍

2017-04-27 20:49 UTC, kariabancroft commented on .github/PULL_REQUEST_TEMPLATE
> +| Describe how you approached testing your API Wrapper, what edge cases do you take? |  |
Maybe this could be simplified to "Describe an edge case or failure case test you wrote for your API Wrapper"

2017-04-27 20:49 UTC, kariabancroft commented on README.md
> +This is an individual, [stage 2](https://github.com/Ada-Developers-Academy/pedagogy/blob/master/rule-of-three.md) project.
Should we add a Trello requirement since we are not providing the project in waves to practice these skills?

2017-04-27 20:49 UTC, kariabancroft commented on .github/PULL_REQUEST_TEMPLATE
> +| What is the Heroku URL of your deployed application? |  |
This isn't in the requirements so if we want them to deploy it we should add it

2017-04-27 20:49 UTC, kariabancroft commented on feedback.md
> +|  **Overall** |  |
We should add something for API attribution (since that's in the requirements for using the API)

2017-04-27 20:49 UTC, kariabancroft commented on feedback.md
> +|  **Overall** |  |
We should ensure the API key isn't saved in the cassettes (noted from dan's original spreadsheet from C6)

2017-04-27 20:49 UTC, kariabancroft commented on feedback.md
> +|  **Overall** |  |
Show view opens recipe in a new tab

2017-04-29 04:23 UTC, CheezItMan commented on README.md
> +This is an individual, [stage 2](https://github.com/Ada-Developers-Academy/pedagogy/blob/master/rule-of-three.md) project.
Added

2017-04-29 04:25 UTC, CheezItMan commented on .github/PULL_REQUEST_TEMPLATE
> +| What is the Heroku URL of your deployed application? |  |
Added

2017-04-29 04:27 UTC, CheezItMan commented on feedback.md
> +|  **Overall** |  |
added.

2017-04-29 04:27 UTC, CheezItMan commented on .github/PULL_REQUEST_TEMPLATE
> +| Describe how you approached testing your API Wrapper, what edge cases do you take? |  |
added

2017-04-29 20:10 UTC, kariabancroft approved these changes

2017-04-29 20:10 UTC, merged